language: python
sudo: false
dist: trusty
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - 'nightly'
matrix:
  allow_failures:
    - python: 'nightly'
before_install:
  - |
    python -m pip install \
        pip setuptools \
        pytest-cov "mock ; python_version < '3'" \
        sphinx
install:
  - python -m pip install .
script:
  - python -m pytest --pyargs dqsegdb2 --cov dqsegdb2
  - python setup.py build_sphinx -W
after_success:
  - python -m pip install coveralls
  - coveralls
cache: pip
