steps:
- task: Cache@2
  inputs:
    key: 'conda | "$(Agent.OS)" | "python${PYTHON_VERSION}" | "$(System.JobName)"'
    path: $(CONDA_PKGS_DIRS)
    restoreKeys: |
      conda | "$(Agent.OS)" | "python${PYTHON_VERSION}"
  displayName: Cache Conda packages

- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH (Linux)
  condition: eq( variables['Agent.OS'], 'Linux' )

- bash: |
    echo "##vso[task.prependpath]$CONDA/bin"
    sudo chown -R $USER $CONDA
  displayName: Add conda to PATH (macOS)
  condition: eq( variables['Agent.OS'], 'Darwin' )

- powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
  displayName: Add conda to PATH (Windows)
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

- bash: |
    conda config --set always_yes yes
    conda config --add channels conda-forge
    conda info --all
    conda config --show-sources
    conda list --show-channel-urls
  displayName: Configure Conda
