jobs:
- job: Docs
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
  - script: |
      python3 -m pip install \
          --upgrade \
          --upgrade-strategy eager \
          --requirement requirements-docs.txt
    displayName: "Install build requirements"
  - script: |
      cd docs
      python3 -m sphinx -b html . $(Build.ArtifactStagingDirectory)
    displayName: "Build documentation"
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: Docs
