jobs:
- job: Docs
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    CONDA_PKGS_DIRS: $(Pipeline.Workspace)/.conda/pkgs
    PYTHON_VERSION: '3.9'
  steps:
  - template: conda.yml
  - bash: |
      conda create --name docs --yes --quiet \
          "python=${PYTHON_VERSION}" \
          --file requirements.txt \
          --file requirements-docs.txt \
      ;
    displayName: "Create docs environment"
  - bash: |
      source activate docs
      python -m pip install .
    displayName: "Install DQSegDB2"
  - bash: |
      cd docs
      source activate docs
      python -m sphinx -b html -n -W . $(Build.ArtifactStagingDirectory)
    displayName: "Build documentation"
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: Docs
