jobs:
- job: Test
  strategy:
    matrix:
      'Linux Python 3.6':
        imageName: 'ubuntu-latest'
        PYTHON_VERSION: '3.6'
      'Linux Python 3.7':
        imageName: 'ubuntu-latest'
        PYTHON_VERSION: '3.7'
      'Linux Python 3.8':
        imageName: 'ubuntu-latest'
        PYTHON_VERSION: '3.8'
      'macOS Python 3.6':
        imageName: 'macOS-latest'
        PYTHON_VERSION: '3.6'
      'macOS Python 3.7':
        imageName: 'macOS-latest'
        PYTHON_VERSION: '3.7'
      'macOS Python 3.8':
        imageName: 'macOS-latest'
        PYTHON_VERSION: '3.8'
      'Windows Python 3.6':
        imageName: 'windows-latest'
        PYTHON_VERSION: '3.6'
      'Windows Python 3.7':
        imageName: 'windows-latest'
        PYTHON_VERSION: '3.7'
      'Windows Python 3.8':
        imageName: 'windows-latest'
        PYTHON_VERSION: '3.8'

  pool:
    vmImage: $(imageName)

  variables:
    CONDA_PKGS_DIRS: $(Pipeline.Workspace)/.conda/pkgs

  steps:
  - checkout: none

  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: 'Sources'
      downloadPath: '.'
    displayName: Download sources

  # install and configure conda
  - template: conda.yml

  - bash: |
      conda create --name ci --yes --quiet \
          "python=${PYTHON_VERSION}" \
          "pip" \
          "setuptools" \
      ;
    displayName: "Create environment"

  - bash: tar -xvf Sources/dqsegdb2-*.tar.gz --strip-components 1 */requirements.txt
    displayName: "Extract requirements (macOS)"
    condition: eq( variables['Agent.OS'], 'Darwin' )

  - bash: tar -xvf Sources/dqsegdb2-*.tar.gz --strip-components 1 --wildcards */requirements.txt
    displayName: "Extract requirements (not-macOS)"
    condition: ne( variables['Agent.OS'], 'Darwin' )

  - bash: conda install --quiet --yes --update-deps --name ci --file requirements.txt
    displayName: "Install requirements"

  - bash: |
      source activate ci
      python -m pip install Sources/dqsegdb2-*.tar.gz
    displayName: "Install DQSegDB2"

  - bash: conda list --name ci
    displayName: "List packages"

  - bash: |
      source activate ci
      python -m pytest -rs --verbose --cov dqsegdb2 --pyargs dqsegdb2 --junitxml=junit.xml --cov-report=xml --cov-report=html
    displayName: "Run tests"

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: "junit.xml"
      testResultsFormat: "JUnit"

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'

  - bash: |
      source activate ci
      conda install --yes --quiet coverage
      PLATFORM=$(echo $(Agent.OS) | cut -d_ -f1)
      bash <(curl -s https://codecov.io/bash) -F ${PLATFORM},python${PYTHON_VERSION/./}
    displayName: 'Upload to codecov.io'
