name: Documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sphinx:
    # -----------------------
    # Generate the documentation
    # -----------------------
    name: Sphinx

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Get source code
      uses: actions/checkout@v2

    - name: Configure conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: docs
        channels: conda-forge
        python-version: '3.9'

    - name: Conda info
      run: conda info --all

    - name: Install dependencies
      run: conda create --name docs --yes --quiet --file requirements.txt --file requirements-docs.txt

    - name: Install DQSegDB2
      run: python -m pip install . --no-build-isolation -vv

    - name: Package list
      run: conda list --name docs

    - name: Build documentation
      run: |
        cd docs
        python -m sphinx -b html -n -W . _build

    - name: Upload documentation build
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs/_build
